### ISSUE TITLE
websocket is not created correctly in a proxied environment

### ISSUE THREAD

**Issue by wgnann** [Evidlo/picklecast#2]
Since the websocket address is created using `window.location.hostname`, any information regarding the true URL (e.g. the custom port) is missed.
https://github.com/Evidlo/picklecast/blob/1ae55d17b0bf4c8b5ff5f30fea1f84f9bd46bd33/picklecast/webrtc.js#L25

One possible fix would be to use `window.location.href` and strip the `https://` part and the `display` part, if exists.

Example: `window.location.href.replace("https://","").replace("display","")`.

**Comment by Evidlo** [comment]
Should be fixed now.
