### ISSUE TITLE
install_service throws an error

### ISSUE THREAD

**Issue by pascalin** [Evidlo/picklecast#4]
Hello, thank you very much for your work. I am trying picklecast, but when trying to install it as a service I get the following error:

> Traceback (most recent call last):
>   File "/home/user/.env/bin/picklecast", line 33, in <module>
>     sys.exit(load_entry_point('picklecast==1.0.2', 'console_scripts', 'picklecast')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.env/lib/python3.11/site-packages/picklecast/picklecast.py", line 198, in main
>     args.func(**vars(args))
>   File "/home/user/.env/lib/python3.11/site-packages/picklecast/picklecast.py", line 138, in install_service
>     service = base_dir.joinpath("picklecast.service")
>               ^^^^^^^^
> NameError: name 'base_dir' is not defined

What is wrong here?

**Comment by Evidlo** [comment]
This should be fixed in the latest version 1.0.3.  Let me know what happens.

**Comment by pascalin** [comment]
Great! I will try it. Thank you.

**Comment by pascalin** [comment]
I got a FileNotFound error:

> Traceback (most recent call last):
>   File "/home/user/.env/bin/picklecast", line 33, in <module>
>     sys.exit(load_entry_point('picklecast==1.0.3', 'console_scripts', 'picklecast')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.env/lib/python3.11/site-packages/picklecast/picklecast.py", line 214, in main
>     args.func(**vars(args))
>   File "/home/user/.env/lib/python3.11/site-packages/picklecast/picklecast.py", line 146, in install_service
>     dest.write_text(service_text)
>   File "/usr/lib/python3.11/pathlib.py", line 1079, in write_text
>     with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/pathlib.py", line 1045, in open
>     return io.open(self, mode, buffering, encoding, errors, newline)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.config/systemd/user/picklecast.service'

Creating the folder and copying the .service file from picklecast distributed files should solve the issue:

> $ mkdir -p /home/user/.config/systemd/user/
> $ cp /home/user/env/lib/python3.11/site-packages/picklecast/picklecast.service /home/user/.config/systemd/user/
> $ picklecast install_service
> Installed service to /home/kiosk/.config/systemd/user/picklecast.service
> Enable the service by running:
>     systemctl --user daemon-reload
>     systemctl --user start picklecast

**Comment by Evidlo** [comment]
Thanks, I've fixed that too.

**Comment by pascalin** [comment]
Thank you :+1:  It's is working now.
